live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[font]
size = 9

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Medium"

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Option"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Option"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Option"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Option"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Option"
