[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11

[font.bold]
family = "AnonymicePro Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "AnonymicePro Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "AnonymicePro Nerd Font Mono"
style = "Italic"

[font.normal]
family = "AnonymicePro Nerd Font Mono"
style = "Regular"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Option"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Option"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Option"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Option"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Option"

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[window]
dynamic_padding = false
opacity = 0.9

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 8
y = 8
