live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[cursor]
style = "Block"
vi_mode_style = "Block"

[env]
TERM = "xterm-256color"

[window]
dynamic_padding = false
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 2
y = 2

[scrolling]
history = 5000

[selection]
save_to_clipboard = true

[font]
size = 10

[font.normal]
family = "BlexMono Nerd Font Mono"
style = "Medium"

[font.bold]
family = "BlexMono Nerd Font Mono"
style = "Bold"

[font.italic]
family = "BlexMono Nerd Font Mono"
style = "Italic"

[font.bold_italic]
family = "BlexMono Nerd Font Mono"
style = "Bold Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Option"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Option"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Option"

[[keyboard.bindings]]
action = "ClearLogNotice"
key = "L"
mods = "Option"

[[keyboard.bindings]]
chars = "\f"
key = "L"
mods = "Option"

# cyberdream theme for alacritty
[[colors.indexed_colors]]
color = "0xffa066"
index = 16

[[colors.indexed_colors]]
color = "0xff5d62"
index = 17

[colors.bright]
black = "0x727169"
blue = "0x7fb4ca"
cyan = "0x7aa89f"
green = "0x98bb6c"
magenta = "0x938aa9"
red = "0xe82424"
white = "0xdcd7ba"
yellow = "0xe6c384"

[colors.normal]
black = "0x090618"
blue = "0x7e9cd8"
cyan = "0x6a9589"
green = "0x76946a"
magenta = "0x957fb8"
red = "0xc34043"
white = "0xc8c093"
yellow = "0xc0a36e"

[colors.primary]
background = "0x16181a"
foreground = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"
