return {
    "nvim-treesitter/nvim-treesitter",
    dependencies = { "nvim-treesitter/nvim-treesitter-context" },
    opts = {
        sync_install = false,
        auto_install = true,
        indent = { enable = true },
        highlight = {
            enable = true,
            additional_vim_regex_highlighting = { "markdown" },
        },
        ignore_install = { "org" },
        ensure_installed = {
            "bash",
            "comment",
            "c",
            "cmake",
            "cpp",
            "css",
            "dockerfile",
            "dot",
            "git_config",
            "git_rebase",
            "gitattributes",
            "gitcommit",
            "gitignore",
            "go",
            "graphql",
            "gomod",
            "gosum",
            "gowork",
            "html",
            "http",
            "java",
            "javascript",
            "json",
            "json5",
            "lua",
            "make",
            "prisma",
            "python",
            "regex",
            "rust",
            "scala",
            "sql",
            "svelte",
            "vue",
            "tmux",
            "toml",
            "tsx",
            "typescript",
            "xml",
            "yaml",
            "zig",
        },
    },
    init = function()
        require("nvim-treesitter.install").update({ with_sync = true })
    end
}
